description: "Complaint Classification Eval"

prompts:
  - prompts.py:basic_prompt
  - prompts.py:improved_prompt
  
providers:
  - id: openai:Phi-3.5-mini-instruct
    config:
      apiKey: github_api_key
      apiBaseUrl: https://models.inference.ai.azure.com

tests: dataset.csv

