description: "Animal Legs Eval"

prompts:
  - prompts.py:simple_prompt
  - prompts.py:better_prompt
  - prompts.py:chain_of_thought_prompt
  
providers:
  - id: localai:llama-3.2-3b-instruct-q4_k_m
    config:
      apiKey: your_api_key_here
      apiBaseUrl: http://192.168.1.111:8880/v1
  - id: localai:phi-3.5-mini-instruct
    config:
      apiKey: your_api_key_here
      apiBaseUrl: http://192.168.1.111:8880/v1 

tests: animal_legs_tests.csv

defaultTest:
  options:
    transform: file://transform.py


